export { default as main } from './main.web'
export { default as contact } from './contact.web'
export { default as about } from './about.web'
export { default as articles } from './articles.web'
export { default as history } from './history.web'
